# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    types: ["opened", "edited"]
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  audit:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install npm packages 
        run: npm ci
      - name: Audit npm packages 
        run: |
          npm audit > audit-report
          cat audit-report
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./audit-report
          comment_tag: execution
