# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  verify-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm packages 
        run: npm ci
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 14
          cache: npm
      - name: Install npm packages 
        run: npm ci
      - name: Audit npm packages
        run: npm test
        continue-on-error: true
    needs: verify-install
  
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 14
          cache: npm
      - name: Install npm packages 
        run: npm ci
      - name: Audit npm packages 
        run: |
          npm audit > audit-report
          cat audit-report
        continue-on-error: true
      - name: Upload audit results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: audit-report
          path: ./audit-report
    needs: verify-install

  report-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Download report
        uses: actions/download-artifact@v4.1.4
        with:
          name: audit-report
      - name: Show report
        run: cat audit-report
      - name: PR comment with file
        if: ${{ github.event_name == 'pull_request' && always() }} 
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./audit-report
          comment_tag: execution
    needs: audit
  
  build:
    #if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set owner name to lowercase
        run: echo "LC_DOCKER_USER=${DOCKER_USER,,}" >> ${GITHUB_ENV}
      - name: Build docker container
        run: docker build -t ghcr.io/${LC_DOCKER_USER}/${GITHUB_REPOSITORY#*/}/dummy-app:1.0 .
      - name: Push docker container
        run: docker push ghcr.io/${LC_DOCKER_USER}/${GITHUB_REPOSITORY#*/}/dummy-app:1.0
    env:
      DOCKER_USER: ${{ github.actor }}
    needs: [ audit, test]
